services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER:-docker}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docker}
    ports:
      - '5442:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
